### ISSUE TITLE
ObjectiveRFun Examples

### ISSUE THREAD

**Issue by pfistfl** [mlr-org/bbotk#104]
ObjectiveRFun currently does not have any examples, could do with a simple one!

**Comment by jakob-r** [comment]
You suggest A) predefined functions like in smoof or B) a written down example?
I guess I really want A).

**Comment by pfistfl** [comment]
I meant B) as a short term thing, A would be great but this is more long term.

**Comment by jakob-r** [comment]
I just copied the stuff from the README
