### ISSUE TITLE
OptimInstance$eval_batch ignores .objective_multiplicator

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#108]
OptimInstance$objective_function multiplies objectives that should be maximized with -1, but $eval_batch does not. 

(Also, I hope you guys thought this through with $objective_function returning a value that differs from what will be in the archive)

**Comment by mb706** [comment]
P.S. This line would probably fail if a param has more than one tag (e.g. a tag that is neither "minimize" nor "maximize")

https://github.com/mlr-org/bbotk/blob/166e3e510ca28eb6ce4e0580de28f43b2a7ad911/R/OptimInstance.R#L55

**Comment by jakob-r** [comment]
`OptimInstance$objective_function` is just an interface so that you can use the `OptimInstance` from external optimizers like `optim()`. So we do not want to log the (eventually) negated output. 
In all other parts of bbotk we never negate y for the output. 
Do you have a suggestion how we can make this more clear / Do you still think there is something wrong?

PS: I will fix the tag issue.

**Comment by jakob-r** [comment]
Tag issue is fixed

**Comment by mb706** [comment]
Some thoughts on this:
* I found it confusing that objective_function behaves differently from eval_batch, I would prefer if they behave in the same way
* Maybe the best solution is to have an argument that switches between actual values and values multiplied to minimization, for all things that get objective values (objective_function, eval_batch, things with which the archive is accessed, etc)
* objective_multiplicator should probably be publicly accessible

**Comment by berndbischl** [comment]
> * objective_multiplicator should probably be publicly accessible

this we can do

for the rest you would need to argue @mb706 why you really need this. atm interface and semantics seem clear to me.
which is:
- you get "unchanged" values everywhere. 
- OptimInstance$objective_function is convenience sugar - which is always minimized

seems pretty clear and good to me?

**Comment by be-marc** [comment]
> objective_multiplicator should probably be publicly accessible

Done by https://github.com/mlr-org/bbotk/commit/e142962c55c00e11b62e796166c0886782094d11.
