### ISSUE TITLE
Better document logger message origins

### ISSUE THREAD

**Issue by pat-s** [mlr-org/bbotk#109]
In the book at https://mlr3book.mlr-org.com/logging.html but also within the package.

It is not obvious for users that they need to set `lgr::get_logger("bbotk")$set_threshold("warn")` (example) to suppress tuning output.
Naturally they would try with the mlr3 or mlr3tuning logger.
Internally we know of {bbotk} but a user never really gets in contact with it and hence does not think of altering this logger environment.

I wonder if there is a need to add more info to the help pages of certain tuning functions as well which logger level actually applies?

Or, even more verbose, prefix the log output with the package name?

```r
INFO  [11:19:17.759] bbotk: Starting to optimize 1 parameter(s) with '<OptimizerGridSearch>' and '<TerminatorNone>' 
INFO  [11:19:17.762] bbotk: Evaluating 1 configuration(s) 
INFO  [11:19:18.061] bbotk: Result of batch 1: 
```

**Comment by be-marc** [comment]
* The book is fixed
* We mention the logger in the mlr3tuning and mlr3fselect cheatsheet
* All tuners have a section called logging

I think you are right that this might still not enough. We can prefix the logging messages quiet easily with: 

```
lg = get_logger("bbokt")
f = function(event) {
  cat("bbotk: ")
  TRUE
}
lg$add_filter(f)
lg$error("Test")

> bbotk: ERROR [22:36:09.822] Test 
```
We just need to add this to mlr3 and bbotk in `zzz.R`.

@mllg @berndbischl

**Comment by jakob-r** [comment]
Hmm. If you use mlr3tuning you probably dont know bbotk and it can get confusing? So maybe the object that does the logging should make itself "visible"?

**Comment by be-marc** [comment]
Logging messages look like this now:

```
INFO  [13:21:26.187] [bbotk] Starting to optimize 2 parameter(s) with '<OptimizerGenSA>' and '<TerminatorEvals>' 
INFO  [13:21:26.259] [bbotk] Evaluating 1 configuration(s) 
INFO  [13:21:26.278] [bbotk] Result of batch 1: 
INFO  [13:21:26.284] [bbotk]         x1        x2        y 
INFO  [13:21:26.284] [bbotk]  -3.236372 -4.430809 -19.4668 
INFO  [13:21:26.308] [bbotk] Evaluating 1 configuration(s) 
```
