### ISSUE TITLE
logging in Rmd interactive: Rstudio seems to catch every print() of a data.table

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/bbotk#124]
... and puts it as some weird output under a chunk in the default settings.

R Console has incomplete output:
![image](https://user-images.githubusercontent.com/1888623/104433784-c68e6280-558a-11eb-9c9b-525dc964e1ad.png)

Output is shown in extra items:
![image](https://user-images.githubusercontent.com/1888623/104433679-aa8ac100-558a-11eb-8a9f-5180e4db91eb.png)

Origin:
https://github.com/mlr-org/bbotk/blob/a892bae70f31098f706afc33828c869f3efa1905/R/OptimInstance.R#L151-L153

This is no bug of bbotk but apparently RStudio crashes if a chunk generates many data table outputs.

It looks like the following is not getting caught:
```r
x = capture.output(data.table:::print.data.table(data.table(1,2), class = FALSE, row.names = FALSE, print.keys = FALSE))
print(x)
```
as well as
```r
x = capture.output(print.data.frame(data.table(1,2), class = FALSE, row.names = FALSE, print.keys = FALSE))
print(x)
```

**Comment by jakob-r** [comment]
Let's see what if the RStudio issue has an effect: https://github.com/rstudio/rstudio/issues/8732

**Comment by be-marc** [comment]
Quarto shows the same behavior. We can't fix this. Use `lgr::get_logger("bbotk")$set_threshold(0)` to avoid.
