### ISSUE TITLE
Remove is_terminated from OptimInstance

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#126]
I see no reason why the user sholdn't be allowed to change the termination criterion of a `OptimInstance` and then continue optimizatoin, possibly with a different tuner. Currently this is made unnecessarily difficult because the user also has to reset `$is_terminated`.

`$is_terminated` is currently also used for printing, but why not evaluate it dynamically (turn `$is_terminated` into an active binding)? It shouldn't be that expensive.

**Comment by be-marc** [comment]
`Optimizer$optimize(instance)` could set `instance$is_terminated = FALSE`. This is done before the first termination check is called. So the user does not have to change it manually anymore. Are you okay with that?

**Comment by be-marc** [comment]
But I am also unsure why we implemented this slot.

**Comment by mb706** [comment]
Resetting in `$optimize` would still make `archive$eval_batch()` not work, imho even more confusing. I'd still vote for removing `is_terminated`.

**Comment by berndbischl** [comment]
i am fine with making this an AB. but the user needs to be able to ask? 
what is the current proposal / summary?

**Comment by mb706** [comment]
https://github.com/mlr-org/bbotk/pull/127
