### ISSUE TITLE
Prettier printing of `Archive`?

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#130]
It would be nice if printed archives were less wide, and had more chance to fit on a single terminal row even with default width 80. The printer of `Archive` could show a reduced data.table of evaluations; if the user wants to see the full data he can still use `$data`.

* The 'x_domain' column is not interesting because it will always just say 'list'
* numeric columns could be shown with less precision (i.e. fewer digits)
* maybe consider even removing the timestamp column

**Comment by be-marc** [comment]
Closed by c6f0ab463390a8a888909da96af6d81f03aa2d08.
* Hide `x_domain` column
* Numeric columns only use 2 significant digits
