### ISSUE TITLE
Co-occurring names in domain and codomain are a bit broken

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#131]
When the same name comes up in an objective's domain and codomain, then there are duplicate columns in the resulting archive.

```r
objective <- ObjectiveRFun$new(
  fun = function(xs) list(x = xs$x + 10),
  domain = ps(x = p_dbl(-2, 4), y = p_dbl(-2, 4)),
  codomain = ps(x = p_dbl(tags = "maximize"))
)
oi <- OptimInstanceSingleCrit$new(objective, terminator = trm("none"))

oi$eval_batch(data.table(x = 1, y = 2))

oi$archive$data
#>    x y  x  x_domain           timestamp batch_nr
#> 1: 1 2 11 <list[2]> 2021-02-28 19:27:24        1
```
should an error be thrown when an objective / OptimInstance is created where the output space and search space have overlapping names?  -- or when any of them have the name `x_domain`, `timestamp`, `batch_nr`, ...?

**Comment by be-marc** [comment]
Closed by 9f3e1ca01489e83593744b5cebcc7c534b7719c0
