### ISSUE TITLE
current user-way to define objective feels very clumsy

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/bbotk#14]
i now wrote this due to the dt interface....

```
fn = function(dt) {
  y = map_dbl(seq_row(dt), function(i) {
    x = dt[i,]
    sum(x^2)
  })
  data.table(y = y)
}
```

**Comment by mllg** [comment]
Are we already thinking about sugar?

**Comment by berndbischl** [comment]
i wouldnt really call this sugar. i really dont like the look of the above.
this is what i wrote for a multivariate testcase

f1 = function(x) sum(unlist(x)^2)
f2 = function(x) sum(unlist(x)^2-1)
fn = function(dt) {
  y = map_dbl(seq_row(dt), function(i) {
    x = dt[i,]
    data.table(y1 = f1(x), y2 = f2(x))
  })
  rbindlist(y)
}

**Comment by berndbischl** [comment]
you can call this sugar, and we can push the discussion back, but i think at some point this needs to be adressed. if you want to call it non-urgent for now: fine

**Comment by berndbischl** [comment]
it is a list for now
