### ISSUE TITLE
where do optimizers store their result?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/bbotk#15]
in the archive? the objective? do they simply rerurn it?

**Comment by mllg** [comment]
Do you mean `Tuner` instead of `Optimizer`?

**Comment by mllg** [comment]
Or the optimizer of the AF?

**Comment by berndbischl** [comment]
"Tuners" as term does no exist in the package, it would be an "Optimizer" - which is basically the same thing. and the package also know nothing about acquisition functions? 

The question is where, after an optimizer has optimized the objective function, the result is stored.

**Comment by berndbischl** [comment]
probably on optimizer should decide, given the archive, what it wants to return?

**Comment by berndbischl** [comment]
related to #16

**Comment by be-marc** [comment]
Currently, the optimizer stores the best result in the `result` slot of the  `OptimInstance` and returns the result. Close?

**Comment by jakob-r** [comment]
Yes. A more specific issue can be opened if needed
