### ISSUE TITLE
documentation of `is_dominated`

### ISSUE THREAD

**Issue by sumny** [mlr-org/bbotk#152]
The documentation states:
`Calculates which points are not dominated, i.e. points that belong to the Pareto front.`

However, looking at the return value and how it is being used (and also the name of the function) it looks like the points that are actually dominated are retruned and `!is.dominated(X)` would actually return points belonging to the Pareto front?

**Comment by be-marc** [comment]
Yes you are right. The emoa documentation states 

> `is_dominated` returns which points from a set are dominated by another point in the set. 

Our documentation was wrong but we used it right. Thanks!

5091be7a9cde50a94bc966bc94055ecbfc454f45
