### ISSUE TITLE
TunerIrace fails when a param in the paramset has multiple dependencies

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#188]
It fails with this one, for example: https://github.com/slds-lmu/yahpo_data/blob/main/rbv2_super/param_set.R . `paradox_to_irace` then creates a broken parameter description string where some parameters occur multiple times (due to recycling).

**Comment by be-marc** [comment]
> Is there anything irace can do about this?

No. This was an issue on our side. Thanks.

**Comment by be-marc** [comment]
Solved by #195
