### ISSUE TITLE
The handling of trafos and the various $eval(), $eval_batch(), $eval_dt() things are more difficult than they should be

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#189]
We should think about how to make handling of the various `$eval_**()` functions easier. I had to write a few functions that were wrapping other Objectives or TuningObjectives. Calling `$eval_many()` from inside the `.fun` of a `ObjectiveRFunDt` doesn't straightforwardly work when there are missings or trafos involved. I needed to use [`Design`](https://github.com/slds-lmu/paper_2022_reliable_mbo/blob/5f91e7bbff3bbc5ae7227ce7d44769990fde654f/R/yahpo.R#L105), but it feels wrong to construct an object when what I want to do is transform one value to another.

[Having to re-invent the TunerObjective](https://github.com/slds-lmu/paper_2022_reliable_mbo/blob/5f91e7bbff3bbc5ae7227ce7d44769990fde654f/R/actual.R#L102-L108) should also not be necessary when I need to more things during tuning than just benchmarking.

**Comment by be-marc** [comment]
Yes, missings are a bit tricky with data tables. Missings are `NA` in a data table but `NA` can also be a valid parameter value. We decided that the user needs to handle `NA`s / Missings when using `ObjectiveRFunDt`. But I'm looking forward to hearing your thoughts.

> [Having to re-invent the TunerObjective](https://github.com/slds-lmu/paper_2022_reliable_mbo/blob/5f91e7bbff3bbc5ae7227ce7d44769990fde654f/R/actual.R#L102-L108) should also not be necessary when I need to more things during tuning than just benchmarking.

Shouldn't that soon be possible with callbacks?

**Comment by mb706** [comment]
Turns out, one problem with ObjectiveRFunDt is that, if the search space has a trafo, `eval_many` is called with the transformed values (`xss`, list of list of param values). ObjectiveRFunDt then assembles a data.table from that list by calling rbindlist. If the `xss` is short, e.g. only contains one paramester configuration point, and if a hyperparameter is missing, then the column for that hyperparameter is not going to be there.

I had to resort to [this hack](https://github.com/slds-lmu/paper_2022_reliable_mbo/blob/5f91e7bbff3bbc5ae7227ce7d44769990fde654f/R/yahpo.R#L89-L105) to make sure the missing columns are there, since the underlying function relied on the columns all being there and having the right type (and being NA if necessary).

**Comment by mb706** [comment]
[this rbindlist](https://github.com/mlr-org/bbotk/blob/57b3d9ad23f591b00429a6494b5cfe7dde6b8e3c/R/ObjectiveRFunDt.R#L48) should be augmented to make sure all required columns are there (and have the right type)

**Comment by mb706** [comment]
Also suggestion: ObjectiveRFunMany (?) where the given `fun` is called with the `xss` through `eval_many`

**Comment by be-marc** [comment]
> [this rbindlist](https://github.com/mlr-org/bbotk/blob/57b3d9ad23f591b00429a6494b5cfe7dde6b8e3c/R/ObjectiveRFunDt.R#L48) should be augmented to make sure all required columns are there (and have the right type)

Solved by #198. Improves  #143.

**Comment by be-marc** [comment]
> Also suggestion: ObjectiveRFunMany (?) where the given fun is called with the xss through eval_many

#199
