### ISSUE TITLE
Use maximal resolution when reading in parameters

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#191]
The [`readParameters` call here](https://github.com/mlr-org/bbotk/blob/57b3d9ad23f591b00429a6494b5cfe7dde6b8e3c/R/helper_irace.R#L19) has the argument `digits`. I think it should be set to something large (maybe `Inf`, if irace allows this); otherwise we get in trouble since irace rounds the parameter bounds. If it gets rounded in the wrong direction (e.g. lower bound `1e-5`  to `0`) then irace sometimes tries invalid configurations.

**Comment by MLopez-Ibanez** [comment]
How is possible the irace tries invalid configurations? Do you have an example?

Also, R is not infinite precision. Beyond 15 decimals places, the additional values are basically random numbers.

**Comment by mb706** [comment]
The problem is apparently that [this `round()` call](https://github.com/MLopez-Ibanez/irace/blob/48b0c4beda4c7cfcc6e201662c3ef486deb0b97d/R/readParameters.R#L354) sometimes results in `irace` seeing parameter bounds that are too wide; e.g. when the [actual lower bound is `1e-5`](https://github.com/slds-lmu/yahpo_data/blob/9b060ce6dc02846231856e95d2a44cde2285074e/lcbench/param_set.R#L12), then `irace` with the default `readParameters` `digits` value ends up calling the function with value `0`. I am doing quite a lot of experiments currently and observed this often; maybe the mutator in `irace` tries the exact boundary value with nonzero probability? (Another example is lower bound `log(2)` (0.6931472) -> irace tries `0.6931`, which is too low.)

We also accept some [tolerance in our real-valued search space components](https://github.com/mlr-org/paradox/blob/1759598f9d2d87b7c31e993c80069a4f45cf3c1d/R/ParamDbl.R#L39), but that is just much tighter than four digits. I think we should call `irace` in a way that avoids rounding as much as possible.

**Comment by MLopez-Ibanez** [comment]
In irace 3.6 (or 3.5.1) no rounding will occur up to digits=15. Instead an error will be given and the user is expected to adjust 'digits' or the domain. If you don't want to set digits per scenario, my advice would be to call irace with digits=15.

(Probably irace should use paradox to handle parameter spaces and I would support that if someone implemented it without breaking too much backwards compatibility).

**Comment by MLopez-Ibanez** [comment]
Yes, definitely. Those two values are meant to be set together. Most people use the command-line so the values are always the same, but I see that for a pure R user, this is not obvious. 

The API of irace could use some improvements to avoid having these two values separately. Perhaps the parameters structure should carry the digits value and everywhere in irace should use that. This will simplify the interface but I'm not sure if it will make life easier for bbtok.

There is also a TODO item to have digits per parameter, but nobody has ever requested that.

**Comment by be-marc** [comment]
The `digits` parameter in `OptimizerIrace` controls both values now. Solved by #197. Thanks!
