### ISSUE TITLE
allow parallel evals in Evaluator

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/bbotk#20]

**Comment by jakob-r** [comment]
See #23.
Probably encapsulation and parallelization should be handled by the BB function.

**Comment by berndbischl** [comment]
can we maybe document this a bit? what a reasonable would be if the user has to handle this himself? i think this is useful as we discussed this a lot

**Comment by jakob-r** [comment]
Added documentation here: https://github.com/mlr-org/bbotk/commit/6e44a2b2c343c462228e3e4ac0c31fc42d1abf47
