### ISSUE TITLE
consider trafos of paramset. are they done here?

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/bbotk#22]
in evaluator? also make sure they dont happen twice if we connect this to mlr3tuning!

**Comment by jakob-r** [comment]
I would propose to not do any trafo in bbotk. Trafos are only necessary if you are not in control of the BBfunction which is the case in mlr3 but not in general BB optimization where you would just wrap the function and do whatever input preprocessing (transformations) you need to to.
