### ISSUE TITLE
Keep OptimInstanceSingleCrit etc

### ISSUE THREAD

**Issue by mb706** [mlr-org/bbotk#231]
I would suggest keeping OptimInstanceSingleCrit etc. as an alias for OptimInstanceBatchSingleCrit for now, and possibly give a message or warning that the old names are deprecated. Otherwise you introduce a lot of breakage in upstream packages.

**Comment by be-marc** [comment]
Yes we can keep the old instances for now. I added a deprecated message. This will not work for the Optimizer classes but but I think new optimizers are less implemented in the downstream packages.

**Comment by be-marc** [comment]
#232

**Comment by be-marc** [comment]
Done for instances.
