### ISSUE TITLE
Should the terminator return a value between 0 and 1 instead of TRUE, FALSE?

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/bbotk#27]
There are a few interesting approaches of optimizers that change their behavior depending on the progress of the optimization. We could easily support those by having all terminators returning values between 0 and 1, whereas values >= 1 mean that the optimization should terminate.

**Comment by berndbischl** [comment]
please name one relevant example.

**Comment by jakob-r** [comment]
Semi-related: Progress bar

I read somewhere that it might be beneficial to decrease the value of lambda for the LCB acquisition function during the optimization. However, I cannot find the source and it is just something nice to experiment with so probably not a reason to implement it in such a base package.

**Comment by jakob-r** [comment]
Better not change API of terminators but you can always inherit and write an active binding / method that returns the progress
