### ISSUE TITLE
List of lists for opt_x in archive

### ISSUE THREAD

**Issue by be-marc** [mlr-org/bbotk#37]
xss_trafoed should be added as a list of lists to the `Archive` in `add_evals` even when just one parameter is optimized.

**Comment by jakob-r** [comment]
Is that fixed by this commit: https://github.com/mlr-org/bbotk/commit/b83150beac698810786045b9832080c9467e82cb ?

**Comment by be-marc** [comment]
Yes. Added a unit test for this https://github.com/mlr-org/bbotk/commit/0f9619a4d831bcb0e637f8464309744ee47c184e
