### ISSUE TITLE
Define how to use logger

### ISSUE THREAD

**Issue by jakob-r** [mlr-org/bbotk#74]
We have different packages using bbotk "down the line"

- mlr3tuning
- mlr3fselect
- mlr3hyperband
- (mlr3mbo)

This gives us the following hierarchies

- mlr3tuning -> bbotk -> mlr3
- mlr3fselect -> bbtok -> mlr3
- mlr3hyperband -> mlr3tuning -> bbotk -> mlr3
- mlr3mbo -> bbotk
- mlr3mbo -> bbotk -> mlr3
- mlr3tuning -> mlr3mbo -> bbotk -> mlr3
- with the AutoTuner you can put `mlr3 ->` in front of every above point

probably more with pipelines.

Note that probably multiple hierarchies could be active at the same time. So we have to decide how to assign the logger?

**Comment by berndbischl** [comment]
ok, lets start with this. bbotk has his own logger, totally normal.
now the downstream packages define their own loggers. 
is that bad / confusing?

**Comment by jakob-r** [comment]
Only one bbotk logger:
+ Easy
- I might want to see what a tuner/optimizer does but not an underlying feature selection (or similar situation)
