### ISSUE TITLE
Remove all Dictionaries

### ISSUE THREAD

**Issue by be-marc** [mlr-org/bbotk#84]
We could remove `mlr_terminators` and `mlr_optimizers` to have a more basic package with no references to mlr3. The dictionaries are more useful in `mlr3tuning` as `mlr_terminators` and `mlr_tuners`.

**Comment by berndbischl** [comment]
this concerns the complete "sugar" file

**Comment by berndbischl** [comment]
1) The idea was never to delete them but to move them-.

2) My opinion is that they are not needed in bbotk, and if sugar is not needed (and might create problems) we should not have it-

Unfortunately, you have a point with mlr3fselect. I would prefer adding the sugar only in mlr3tuning, but that doesn't work.

Which is "Mist" :(
